### PR TITLE
NetCDF variable attribute search should be case insensitive

### PR DESCRIPTION
**Pull request by mandrakos**
Per the CF Convetions, Section 2.3, "Case is significant in netCDF names, but it is recommended that names should not be distinguished purely by case, i.e., if case is disregarded, no two names should be the same." Therefore the code should allow for any case of the _FillValue (and other) attribute.

Also, fix the spelling of my name :smile:

### CODE REVIEW

**Comment by flamingbear** [comment]
Hi John,

Is this the correct thing to do for all netcdf files or only those that are NetCDF-CF compliant?

the only thing I could find was this:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch02s06.html

I can't imagine that someone has multiple attributes with differing cases, but is that possible?  If so, should we let people decide whether to do a case sensitive search if requested?

Thanks,
Matt

**Comment by mandrakos** [comment]
Hmm, it's possible to have two variables attributes that differ only by case. I've never seen that in practice and think it would be a ridiculous thing to do, but it is possible nonetheless. The problem is that there are some variable attributes hardcoded in ncdf_variable__define.pro, such as _FillValue, and I've run into a NetCDF file that has _FILLVALUE. I'll have to look at how to tailor the changes to allow for case insensitivity for those variable attributes but maintain case sensitivity otherwise.

**Comment by flamingbear** [comment]
I'm clearly kind of bad at managing this in github.  I put a suggested PR back to your master fork. 
https://github.com/mandrakos/coyote/pull/1

Do you think something like that would work?

**Comment by mandrakos** [comment]
Looks good to me.

**Pull request merged**
